language: cpp
sudo: required
compiler: gcc
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libstdc++-8-dev
      - mesa-common-dev
      - libglu1-mesa-dev 
      - freeglut3-dev
os: linux
git:
  submodules: true
env:
  - CONFIGURATION=Debug TESTS=./tests-debug.sh
  - CONFIGURATION=Release TESTS=./tests-release.sh
  - CONFIGURATION=Debug TESTS=./tests-debug.sh USEQT=Y
  - CONFIGURATION=Release TESTS=./tests-release.sh USEQT=Y

before_install:
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - gcc -v && g++ -v && cmake --version
  - ruby prepare_build.rb
  - sudo chmod +x build-travis.sh
  - sudo chmod +x bin/tests-debug.sh
  - sudo chmod +x bin/tests-release.sh
  - IRRKLANG_ROOT="$(pwd)/3rdparty/irrKlang/x64/"
  - export IRRKLANG_ROOT="$(pwd)/3rdparty/irrKlang/x64/"
  - ls $IRRKLANG_ROOT
  - if [[  $USEQT == "Y" ]] ; then sudo apt-add-repository --yes ppa:beineri/opt-qt-5.12.1-xenial  ; fi
  - if [[  $USEQT == "Y" ]] ; then sudo apt-get -qq update  ; fi
  - if [[  $USEQT == "Y" ]] ; then sudo apt-get --yes install qt512base qt512imageformats qt512svg qt512svg qt512tools  ; fi
  - if [[  $USEQT == "Y" ]] ; then ./build-travis-ifaceed.sh $CONFIGURATION; else ./build-travis.sh $CONFIGURATION; fi
script: 
  - cd bin/
  - ls
  - echo "Tests are disabled due to problems with pthreads. If you want, please test using real ubuntu 19.04"
